In [1]:
import pandas as pd

In [2]:
data = {
    "Name": ["John", "Alice", "David", "Emma", "Michael"],
    "Age": [23, 25, 22, 24, 26],
    "Department": ["CSE", "ECE", "IT", "EEE", "MECH"],
    "Marks": [89, 92, 85, 90, 88]
}

df = pd.DataFrame(data)

# Save as CSV
df.to_csv("student_data.csv", index=False)

# Save as Excel
df.to_excel("student_data.xlsx", index=False)

In [3]:
df_csv = pd.read_csv("student_data.csv")

print("CSV Data:")
display(df_csv)

CSV Data:

      Name  Age Department  Marks
0     John   23        CSE     89
1    Alice   25        ECE     92
2    David   22         IT     85
3     Emma   24        EEE     90
4  Michael   26       MECH     88

In [4]:
df_excel = pd.read_excel("student_data.xlsx")

print("Excel Data:")
display(df_excel)

Excel Data:

      Name  Age Department  Marks
0     John   23        CSE     89
1    Alice   25        ECE     92
2    David   22         IT     85
3     Emma   24        EEE     90
4  Michael   26       MECH     88

In [10]:
import pandas as pd
import requests
from io import StringIO

url = "https://en.wikipedia.org/wiki/List_of_countries_by_GDP_(nominal)"

headers = {
    "User-Agent": "Mozilla/5.0"
}

response = requests.get(url, headers=headers)

html = response.text

tables = pd.read_html(StringIO(html))

print("Number of tables found:", len(tables))

df_web = tables[0]

display(df_web.head())

Number of tables found: 8

                                                   0
0  Largest economies in the world by nominal GDP ...